"""
🔍 Data & Grounding / Metadata Explorer
Transparency and trust layer — metadata browser, dataset inventory, validation explanations.
"""
import streamlit as st
import json, sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from ui.styles import get_custom_css
from ui.components import (
    render_section_header, render_insight_card, render_kpi_card,
    render_architecture_card, render_app_footer, render_trust_badges, render_badge,
)
from services.data_loader import (
    load_metadata, load_monthly_revenue, load_country_revenue, load_top_products,
    load_month_country, load_month_product, get_available_files,
)

st.markdown(get_custom_css(), unsafe_allow_html=True)

st.markdown("""
<div class="hero-banner" style="padding: 1.2rem 1.5rem;">
    <h1 style="font-size: 1.6rem;">🔍 Data & Grounding Explorer</h1>
    <div class="hero-subtitle">Inspect the trust layer — metadata, allowed values, processed datasets, and validation logic.</div>
</div>
""", unsafe_allow_html=True)

render_trust_badges()

# ── Why Grounding Matters ──────────────────────────────────────
render_section_header("🛡️", "Why Grounding Matters")
render_architecture_card(
    "🔒", "Preventing Hallucination",
    "The LLM (Gemini) receives only constrained metadata — a list of allowed YearMonth values and Country names — "
    "not the raw transactional dataset. This prevents the model from inventing non-existent time periods, countries, "
    "or metrics. If a user requests 'sales for Narnia in January 2025', the system will detect that neither the country "
    "nor the month exists in the grounded metadata and reject the request before any dashboard artifact is generated."
)
render_architecture_card(
    "✅", "Pydantic Validation",
    "Every DashboardSpec returned by Gemini is validated through a Pydantic model that checks each filter value against "
    "metadata.json. Invalid values raise a ValidationError, ensuring only verified configurations reach the template builder."
)
render_architecture_card(
    "⚙️", "Deterministic Builder",
    "The Power BI Project (.pbip) artifact is generated by cloning a pre-built template and modifying specific JSON targets "
    "(filter objects, title markers, visual containers). No Power BI internals are generated by the LLM — only interpreted."
)

# ── Metadata Overview ──────────────────────────────────────────
render_section_header("📋", "Metadata Overview")
metadata = load_metadata()

ym_list = metadata.get("allowed_yearmonths", [])
country_list = metadata.get("allowed_countries", [])
capabilities = metadata.get("capabilities", {})

k_cols = st.columns(4)
with k_cols[0]:
    render_kpi_card("Allowed Months", len(ym_list), f"{ym_list[0] if ym_list else '—'} → {ym_list[-1] if ym_list else '—'}")
with k_cols[1]:
    render_kpi_card("Allowed Countries", len(country_list), "Validated markets")
with k_cols[2]:
    render_kpi_card("Visual Slots", len(capabilities.get("slots", [])), "Dashboard components")
with k_cols[3]:
    render_kpi_card("Modes", len(capabilities.get("modes", [])), ", ".join(capabilities.get("modes", [])))

# ── Allowed Values Browser ─────────────────────────────────────
render_section_header("📅", "Allowed YearMonth Values")
ym_search = st.text_input("Search months", key="meta_ym_search")
filtered_ym = [ym for ym in ym_list if ym_search.lower() in ym.lower()] if ym_search else ym_list

ym_cols = st.columns(6)
for i, ym in enumerate(filtered_ym):
    with ym_cols[i % 6]:
        st.markdown(render_badge(f"📅 {ym}", "info"), unsafe_allow_html=True)

st.markdown("")
render_section_header("🌍", "Allowed Country Values")
country_search = st.text_input("Search countries", key="meta_country_search")
filtered_countries = [c for c in country_list if country_search.lower() in c.lower()] if country_search else country_list

c_cols = st.columns(4)
for i, c in enumerate(filtered_countries):
    with c_cols[i % 4]:
        st.markdown(render_badge(f"🌍 {c}", "info"), unsafe_allow_html=True)

# ── Capabilities ───────────────────────────────────────────────
render_section_header("⚙️", "System Capabilities")
cap_c1, cap_c2, cap_c3 = st.columns(3)
with cap_c1:
    st.markdown("**Modes**")
    for mode in capabilities.get("modes", []):
        st.markdown(f"• `{mode}`")
with cap_c2:
    st.markdown("**Visual Slots**")
    for slot in capabilities.get("slots", []):
        st.markdown(f"• `{slot}`")
with cap_c3:
    st.markdown("**Metrics**")
    for metric in capabilities.get("metrics", []):
        st.markdown(f"• `{metric}`")

# ── Dataset Inventory ──────────────────────────────────────────
render_section_header("📁", "Processed Dataset Inventory")
files_status = get_available_files()
for fname, exists in files_status.items():
    icon = "🟢" if exists else "🔴"
    status = "Available" if exists else "Missing"
    variant = "success" if exists else "error"
    st.markdown(f"{icon} **{fname}** — {render_badge(status, variant)}", unsafe_allow_html=True)

# ── Mini Preview Tables ────────────────────────────────────────
render_section_header("📊", "Processed Data Previews")

tab1, tab2, tab3, tab4, tab5 = st.tabs(["Monthly Revenue", "Country Revenue", "Top Products", "Month×Country", "Month×Product"])

with tab1:
    df = load_monthly_revenue()
    if not df.empty:
        st.dataframe(df.head(15), use_container_width=True, hide_index=True)
        st.caption(f"{len(df)} rows total")
    else:
        st.info("Data not available.")

with tab2:
    df = load_country_revenue()
    if not df.empty:
        st.dataframe(df.head(15), use_container_width=True, hide_index=True)
        st.caption(f"{len(df)} rows total")
    else:
        st.info("Data not available.")

with tab3:
    df = load_top_products()
    if not df.empty:
        st.dataframe(df.head(15), use_container_width=True, hide_index=True)
        st.caption(f"{len(df)} rows total")
    else:
        st.info("Data not available.")

with tab4:
    df = load_month_country()
    if not df.empty:
        st.dataframe(df.head(20), use_container_width=True, hide_index=True)
        st.caption(f"{len(df)} rows total")
    else:
        st.info("Data not available.")

with tab5:
    df = load_month_product()
    if not df.empty:
        st.dataframe(df.head(20), use_container_width=True, hide_index=True)
        st.caption(f"{len(df)} rows total")
    else:
        st.info("Data not available.")

# ── Validation Examples ────────────────────────────────────────
render_section_header("🧪", "Validation Examples")

examples = [
    ("Show me France in March 2011", "✅ Valid — France ∈ allowed_countries, 2011-03 ∈ allowed_yearmonths", "success"),
    ("Sales for Narnia in 2025-01", "❌ Rejected — 'Narnia' not in allowed_countries, '2025-01' not in allowed_yearmonths", "error"),
    ("Revenue trends for Germany", "✅ Valid — Germany ∈ allowed_countries, no invalid time filter", "success"),
    ("Compare Moon and Mars sales", "❌ Rejected — neither 'Moon' nor 'Mars' in allowed_countries", "error"),
]

for query, explanation, variant in examples:
    st.markdown(f"**Query:** `{query}`")
    st.markdown(f"{render_badge(explanation, variant)}", unsafe_allow_html=True)
    st.markdown("")

# ── Raw Metadata JSON ──────────────────────────────────────────
render_section_header("📄", "Raw Metadata JSON")
with st.expander("View metadata.json"):
    st.code(json.dumps(metadata, indent=2), language="json")

render_app_footer()
